version: '2'
services:
  maid:
    build: ./
    image: chuross/hubot-maid
    container_name: hubot-maid
    environment:
      HUBOT_SLACK_TOKEN:
      HUBOT_MAID_GITHUB_URL: https://api.github.com
      HUBOT_MAID_GITHUB_TOKEN:
