version: '2'
services:
  maid:
    build: ./
    image: chuross/hubot-maid
    container_name: hubot-maid
    links:
      - redis:redis
    environment:
      HUBOT_SLACK_TOKEN:
      HUBOT_MAID_GITHUB_URL: https://api.github.com
      HUBOT_MAID_GITHUB_TOKEN:
  redis:
    image: redis:3.2.3
    container_name: hubot-redis
